version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node-app
    env_file:
      - .env.dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
