# The base image
FROM node:20-alpine AS base
# Set the working directory
WORKDIR /usr/src/app
# copy the package json and package-lock.json
COPY package*.json ./
# Install the dependencies
RUN npm instal


#for production
FROM base AS production
ARG NODE_ENV=production
COPY . .
EXPOSE 5000
RUN npm prune --production
# Set the startup command
CMD ["npm","run", "start"]
